# Generated by Django 4.2.28 on 2026-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('published_at', models.DateTimeField()),
                ('abstract', models.TextField()),
                ('author', models.CharField(max_length=455)),
                ('url', models.URLField(max_length=455)),
                ('title', models.CharField(max_length=455)),
                ('section_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
