# Generated by Django 4.2.11 on 2026-02-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='article_id',
            new_name='article',
        ),
    ]
